services:
  chatsfrontend:
    image: ${DOCKER_REGISTRY-}chatsfrontend
    build:
      context: .
      dockerfile: ChatsFrontend/Dockerfile

  chatswebapi:
    image: ${DOCKER_REGISTRY-}chatswebapi
    build:
      context: .
      dockerfile: ChatsWebApi/Dockerfile

